version: "0.1-beta"

routing:
  model: arch-router

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - name: arch-router
    access_key: $OPENAI_API_KEY
    provider_interface: arch
    model: Arch-Router

  - name: gpt-4o-mini
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o-mini

  - name: gpt-4o
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    default: true

  - name: code_generation
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    usage: Generating new code snippets, functions, or boilerplate based on user prompts or requirements

  - name: code_understanding
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4.1
    usage: understand and explain existing code snippets, functions, or libraries

tracing:
  random_sampling: 100
