version: v0.1.0

routing:
  model: arch-router

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - name: arch-router
    access_key: $ARCH_API_KEY
    provider_interface: arch
    model: hf.co/katanemo/Arch-Router-1.5B.gguf:Q4_K_M
    endpoint: host.docker.internal:11434

  - name: gpt-4o-mini
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o-mini

  - name: gpt-4.1
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4.1
    default: true

  - name: code_generation
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4.1
    usage: generating new code snippets, functions, or boilerplate based on user prompts or requirements

  - name: code_understanding
    provider_interface: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4.1
    usage: understand and explain existing code snippets, functions, or libraries

tracing:
  random_sampling: 100
